steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hexcss/wareflow-landing
      tags: latest
      dockerfile: Dockerfile
      context: .
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  deploy:
    image: bitnami/kubectl:latest
    commands:
      - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
      - export KUBECONFIG=$(pwd)/kubeconfig
      - kubectl apply -f k8s/deployment.yaml -n hexcore-apps
      - kubectl apply -f k8s/service.yaml -n hexcore-apps
      - kubectl apply -f k8s/ingress.yaml -n hexcore-apps
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
